import { NextResponse } from "next/server";
import { authGate, refreshAuthFromMirror } from "@/lib/auth";
import { checkChallengeLimit } from "@/lib/ratelimit";
import { attestedInference, verifiedAnswer, listInference, inferenceStats, refreshInferenceFromMirror, INFERENCE_MODELS, DEFAULT_MODEL, PRICE } from "@/lib/inference";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60; // an attested generation + an attested judge call over the 0G router

// Verified Inference — Merit resells 0G's TEE-attested models over x402 and staples proof to every answer.
// Don't sell AI tokens; sell AI proven to have run correctly (0G TEE attestation) AND proven to be right
// (Merit's verifier, whose judge is itself an attested 0G model). Pay only if it verifies.
//
// POST /api/inference { tier: "attested", prompt, model?, system? }
// POST /api/inference { tier: "verified", question, source, model? }   (charges only on a verified answer, keyed principal)
export async function POST(req: Request) {
  const rl = checkChallengeLimit(Date.now());
  if (!rl.allowed) {
    return NextResponse.json(
      { error: rl.status === 429 ? "rate_limited" : "busy", retryAfterMs: rl.retryMs },
      { status: rl.status, headers: { "Retry-After": String(Math.ceil((rl.retryMs ?? 3000) / 1000)) } },
    );
  }
  let body: { tier?: string; prompt?: string; system?: string; model?: string; question?: string; source?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }
  const tier = (body.tier || "attested").trim();

  await refreshAuthFromMirror().catch(() => {});
  const gate = authGate(req);
  await refreshInferenceFromMirror().catch(() => {});

  if (tier === "attested") {
    const res = await attestedInference({ prompt: body.prompt || "", model: body.model, system: body.system, record: true });
    if ("error" in res) return NextResponse.json({ error: res.error }, { status: res.status });
    return NextResponse.json({
      receipt: res.receipt,
      note: "Attested inference over a 0G TEE-verified model. The attestation handle (provider + request id + res-key) lets anyone retrieve the hardware attestation from 0G. Settle the toll per-call in USDC on Arc via x402.",
    });
  }

  if (tier === "verified") {
    // The GRADE is always real (anyone can see verified/refused). The actual USDC charge only fires for an
    // authenticated principal — and only when the answer verifies. A wrong answer is always $0.
    const settle = gate.ok && !!gate.principal;
    const res = await verifiedAnswer({ question: body.question || "", source: body.source || "", model: body.model, settle, record: true });
    if ("error" in res) return NextResponse.json({ error: res.error }, { status: res.status });
    return NextResponse.json({
      receipt: res.receipt,
      settleNote: settle ? undefined : "Verified in public mode — the verdict is real; connect an API key (Authorization: Bearer <key>) to actually settle the toll (and you still pay $0 if it does not verify).",
      note: "The answer is generated by an attested 0G model and verified by a deterministic numeric gate plus an attested 0G judge. You pay only if it verifies.",
    });
  }

  return NextResponse.json({ error: 'provide { tier: "attested" | "verified" }' }, { status: 400 });
}

// GET /api/inference → the models, per-tier prices, recent attested/verified receipts, and stats
export async function GET() {
  await refreshInferenceFromMirror().catch(() => {});
  return NextResponse.json({
    models: INFERENCE_MODELS,
    defaultModel: DEFAULT_MODEL,
    prices: PRICE,
    recent: listInference(30),
    stats: inferenceStats(),
  });
}
