import { NextResponse } from "next/server";
import { authGate, refreshAuthFromMirror } from "@/lib/auth";
import { checkChallengeLimit } from "@/lib/ratelimit";
import { attestedInference, verifiedAnswer, listInference, inferenceStats, refreshInferenceFromMirror, routeInference, INFERENCE_MODELS, DEFAULT_MODEL, PRICE } from "@/lib/inference";
import { MODELS, type TrustMode } from "@/lib/models";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60; // an attested generation + an attested judge call over the 0G router

// Verified Inference — Merit resells 0G's TEE-attested models over x402 and staples proof to every answer.
// Don't sell AI tokens; sell AI proven to have run correctly (0G TEE attestation) AND proven to be right
// (Merit's verifier, whose judge is itself an attested 0G model). Pay only if it verifies.
//
// POST /api/inference { tier: "attested", prompt, model?, system? }
// POST /api/inference { tier: "verified", question, source, model? }   (charges only on a verified answer, keyed principal)
export async function POST(req: Request) {
  const rl = checkChallengeLimit(Date.now());
  if (!rl.allowed) {
    return NextResponse.json(
      { error: rl.status === 429 ? "rate_limited" : "busy", retryAfterMs: rl.retryMs },
      { status: rl.status, headers: { "Retry-After": String(Math.ceil((rl.retryMs ?? 3000) / 1000)) } },
    );
  }
  let body: { tier?: string; prompt?: string; system?: string; model?: string; question?: string; source?: string; route?: boolean; trust?: string; needVision?: boolean };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }
  const tier = (body.tier || "attested").trim();

  await refreshAuthFromMirror().catch(() => {});
  const gate = authGate(req);
  await refreshInferenceFromMirror().catch(() => {});

  // Verified-quality-per-dollar routing: if no model is pinned and routing is requested (or a trust/vision
  // constraint is given), pick the best model by smoothed pass-rate ÷ price across the full 0G roster.
  let model = body.model;
  let routed: { pick: string; verifiedRate: number; blendedUsdPerM: number; trust: TrustMode } | undefined;
  if (!model && (body.route || body.trust || body.needVision)) {
    const trust = body.trust === "verified" || body.trust === "private" ? (body.trust as TrustMode) : undefined;
    const { ranked, pick } = routeInference({ trust, needVision: body.needVision });
    model = pick;
    const top = ranked.find((r) => r.id === pick);
    if (top) routed = { pick, verifiedRate: Math.round(top.verifiedRate * 1000) / 1000, blendedUsdPerM: top.blendedUsdPerM, trust: top.trust };
  }

  if (tier === "attested") {
    const res = await attestedInference({ prompt: body.prompt || "", model, system: body.system, record: true });
    if ("error" in res) return NextResponse.json({ error: res.error }, { status: res.status });
    return NextResponse.json({
      receipt: res.receipt,
      routed,
      note: "Attested inference over a 0G TEE-verified model. The attestation handle (provider + request id + res-key) lets anyone retrieve the hardware attestation from 0G. Settle the toll per-call in USDC on Arc via x402.",
    });
  }

  if (tier === "verified") {
    // The GRADE is always real (anyone can see verified/refused). The actual USDC charge only fires for an
    // authenticated principal — and only when the answer verifies. A wrong answer is always $0.
    const settle = gate.ok && !!gate.principal;
    const res = await verifiedAnswer({ question: body.question || "", source: body.source || "", model, settle, record: true });
    if ("error" in res) return NextResponse.json({ error: res.error }, { status: res.status });
    return NextResponse.json({
      receipt: res.receipt,
      routed,
      settleNote: settle ? undefined : "Verified in public mode — the verdict is real; connect an API key (Authorization: Bearer <key>) to actually settle the toll (and you still pay $0 if it does not verify).",
      note: "The answer is generated by an attested 0G model and verified by a deterministic numeric gate plus an attested 0G judge. You pay only if it verifies.",
    });
  }

  return NextResponse.json({ error: 'provide { tier: "attested" | "verified" }' }, { status: 400 });
}

// GET /api/inference → the full 0G catalog, the live verified-quality-per-dollar ranking, per-tier prices,
// recent attested/verified receipts, and stats.
export async function GET() {
  await refreshInferenceFromMirror().catch(() => {});
  const { ranked } = routeInference();
  return NextResponse.json({
    models: INFERENCE_MODELS,
    defaultModel: DEFAULT_MODEL,
    catalog: MODELS,
    router: ranked,
    prices: PRICE,
    recent: listInference(30),
    stats: inferenceStats(),
  });
}
